<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <AssemblyName>CodexDeepSeekSetup</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodexDeepSeekSetup.App.Logic\CodexDeepSeekSetup.App.Logic.csproj" />
    <ProjectReference Include="..\CodexDeepSeekSetup.Core\CodexDeepSeekSetup.Core.csproj" />
    <ProjectReference Include="..\CodexDeepSeekSetup.Windows\CodexDeepSeekSetup.Windows.csproj" />
  </ItemGroup>
</Project>
